### ISSUE TITLE
[self setNavTitle:@"" withColor:[UIColor whiteColor]];这个在封装个修改导航栏颜色上去就好了

### ISSUE THREAD

**Issue by 360573078** [sjxt/XTNavigationItemDemo#1]
谢谢大神!

**Comment by sjxt** [comment]
好的  空的时候我看看

**Comment by 360573078** [comment]
感动!!!

**Comment by 360573078** [comment]
self.navigationController.navigationBar.barTintColor
我加了这个去改变背景颜色,出现个问题 颜色为clearColor的时候 效果是黑色,并没有透明!
求大神抽空看看,谢谢!

**Comment by sjxt** [comment]
self.navigationController.navigationBar.translucent = YES;    你设置这个试一试

**Comment by 360573078** [comment]
不行哦,设置透明还是黑色!

**Comment by sjxt** [comment]
你发个demo给我看看吧  邮箱sjxt@sjxt.me
