### ISSUE TITLE
导航栏滑动返回失效

### ISSUE THREAD

**Issue by NatsumeSera** [sjxt/XTNavigationItemDemo#3]
你好 作者 我这里的滑动返回的确没用啊 希望修复一下 测试了好几台手机都没有效果

**Comment by sjxt** [comment]
你好，由于手势可能会出现些问题 所以去掉了 你可以用FDFullscreenPopGesture来实现滑动返回

**Comment by NatsumeSera** [comment]
好的 谢谢
